config/routes.rb
Superuploads::Application.routes.draw do
  get "uploads/index"

  get "uploads/new"

  get "uploads/create"

  get "uploads/show"
  
  resources :uploads, only: [:index, :new, :create, :show]
  
  root to: "uploads#index"
end

app/models/upload.rb
class Upload < ActiveRecord::Base  
  validates_presence_of :description
  validates_presence_of :file_url
  
  delegate :timestamp, :security_hash, to: :credential, prefix: true
  
  attr_writer :credential
    
  private
  
  def credential
    @credential ||= UploadCredential.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
require 'upload_credential'
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(params[:upload])
    if @upload.save
      redirect_to upload_path(@upload)
    else
      render :new
    end
  end

  def show
    @upload = Upload.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_error_notification.html.erb
<% if target.errors.any? %>  
<div class="alert alert-error fade in">
	<!--<a class="close" data-dismiss="alert" href="#">&times;</a>-->
	<h2><%= pluralize(target.errors.count, "error") %> prohibited this <%= target.class.model_name.human  %> from being saved:</h2>  
	<ul>  
		<% target.errors.full_messages.each do |msg| %>  
		<li><%= msg %></li>  
		<% end %>  
	</ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Super Uploads</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Super Uploads", root_path, class: "brand" %>
				<div class="nav-collapse">
					<ul class="nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Uploads <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "All Uploads", uploads_path %></li>
								<li><%= link_to "New Upload", new_upload_path %></li>
							</ul>
						</li>
					</ul>
				</div><!-- /.nav-collapse -->
			</div>
		</div><!-- /navbar-inner -->
	</div>
	<div class="content">
		<%= yield %>
	</div>
	<a href="https://github.com/phstc/uploader_rails"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>
	</body>
</html>

app/views/uploads/index.html.erb
<ul class="breadcrumb">
	<li><%= link_to "Uploads", uploads_path %> <span class="divider">/</span></li>
	<li class="active">All</li>
</ul>

<table class="table">
	<thead>
		<tr>
			<th>#</th>
			<th>File</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<% @uploads.each do | upload | %>
		<tr>
			<td><%= link_to upload.id, upload_path(upload) %></td>
			<td><%= truncate upload.description, length: 40 %></td>
			<td><%= link_to upload.file_url, upload.file_url %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<div class="well">
		<%= link_to "New Upload", new_upload_path, class: "btn btn-primary" %>
</div>

app/views/uploads/new.html.erb
<ul class="breadcrumb">
	<li><%= link_to "Uploads", uploads_path %> <span class="divider">/</span></li>
	<li class="active">New</li>
</ul>

<%= render "layouts/error_notification", target: @upload %>

<form action="/" enctype="multipart/form-data" method="post" id="form_upload" target="iframe_upload" data-security_hash="<%= @upload.credential_security_hash%>" data-timestamp="<%= @upload.credential_timestamp %>">
	<div class="control-group file optional">
		<label class="file optional control-label" for="upload_file">* File</label>
		<div class="controls">
			<input class="file optional" id="upload" name="upload" type="file"><br/>
			<span id="upload_error"></span><span id="upload_percentage"></span>&nbsp;<span id="upload_file_path"><%= link_to_if @upload.file_url.present?, @upload.file_url %></span>
		</div>
	</div>
</form>
<iframe id="iframe_upload" name="iframe_upload"></iframe>

<%= simple_form_for @upload, :html => { :class => 'form-vertical' } do |f| %>
<%= f.input :file_url, as: :hidden %>
<%= f.input :description, as: :text, input_html: {class: "input-xlarge", rows: 10} %>
<div class="form-actions">
	<%= f.button :submit, :class => 'btn-primary' %>
	<%= link_to "Cancel", uploads_path, class: "btn" %>
</div>
<% end %>

<script src="http://ec2-23-22-70-95.compute-1.amazonaws.com/socket.io/socket.io.js"></script>
<%= javascript_include_tag "uploads" %>

app/views/uploads/show.html.erb
<ul class="breadcrumb">
	<li><%= link_to "Uploads", uploads_path %> <span class="divider">/</span></li>
	<li class="active">#<%= @upload.id %></li>
</ul>
	
<p><strong>File</strong><br/> <%= link_to @upload.file_url, @upload.file_url %></p>
<p><strong>Description</strong><br/> <%= simple_format @upload.description %></p>

<div class="well">
	<%= link_to "Back", uploads_path, class: "btn" %>
</div>